# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dcc6b039074ee4d1e988ddeef293880380ac4af7efeb650a1eedb0745865557570d7017a6be17b8bfdf060620b7bb574a568400a8edee8a862efc64dc8a12ea

test:
  secret_key_base: 5733874edadea16c6510a87e2dd36b9ea136d6cad7ae29333a40d9d1869b4fb8beee18f28874741bc58471e35174501b5d268e64bb83a06d3f37f0f5563aee8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
